PublicBodyCategories.add(:pt_PT, [
        "Governo",
            [ "presidencia_do_conselho_de_ministros", "Conselho de Ministros", "Conselho de Ministros" ],
            [ "ministerio_da_administracao_interna", "Administração Interna", "Administração Interna" ],
            [ "ministerio_da_agricultura_e_do_mar", "Agricultura e Mar", "Agricultura e Mar" ],
            [ "ministerio_da_defesa_nacional", "Defesa", "Defesa" ],
            [ "ministerio_da_economia", "Economia", "Economia" ],
            [ "ministerio_da_educacao_e_ciencia", "Educação e Ciência", "Educação e Ciência" ],
            [ "ministerio_da_justica", "Justiça", "Justiça" ],
            [ "ministerio_da_saude", "Saúde", "Saúde" ],
            [ "ministerio_da_solidariedade_emprego_e_seguranca_social", "Solidariedade, Emprego e Segurança Social", "Solidariedade, Emprego e Segurança Social" ],
            [ "ministerio_das_financas", "Finanças", "Finanças" ],
            [ "ministerio_do_ambiente_ordenamento_do_territorio_e_energia", "Ambiente, Ordenamento do Território e Energia", "Ambiente, Ordenamento do Território e Energia" ],
            [ "ministerio_dos_negocios_estrangeiros", "Negócios Estrangeiros", "Negócios Estrangeiros" ],
            [ "gabinete_1º_ministro", "Primeiro Ministro", "Primeiro Ministro" ],
            [ "gabinete_ministro", "Ministros", "Gabinetes de Ministros" ],
            [ "gabinete_secretario_de_estado", "Secretários de Estado", "Secretários de Estado" ],
            [ "gabinete_subsecretario_de_estado", "Sub-Secretários de Estado", "Sub-Secretários de Estado" ],
        "Poder Local",
            [ "area_metropolitana", "Áreas Metropolitanas", "Áreas Metropolitanas" ],
            [ "assembleia_distrital", "Assembleias Distritais", "Assembleias Distritais" ],
            [ "associacao_de_freguesias", "Associações de Freguesias", "Associações de Freguesias" ],
            [ "associacao_de_municipios_de_fins_especificos", "Associações de Municípios", "Associações de Municípios" ],
            [ "camara_municipal", "Câmaras Municipais", "Câmaras Municipais" ],
            [ "comunidade_intermunicipal", "Comunidades Intermunicipais", "Comunidades Intermunicipais" ],
            [ "comunidade_urbana", "Comunidades Urbanas", "Comunidades Urbanas" ],
            [ "junta_de_freguesia", "Juntas de Freguesia", "Juntas de Freguesia" ],
        "Sector Empresarial",
            [ "empresa_intermunicipal", "Empresas Intermunicipais", "Empresas Intermunicipais" ],
            [ "empresa_municipal", "Empresas Municipais", "Empresas Municipais" ],
            [ "entidade_empresarial_municipal", "Entidade Empresarial Municipal", "Entidade Empresarial Municipal" ],
            [ "entidade_publica_empresarial", "Entidade Pública Empresarial", "Entidade Pública Empresarial" ],
            [ "entidade_publica_empresarial_regional", "Entidade Pública Empresarial Regional", "Entidade Pública Empresarial Regional" ],
            [ "agrupamento_complementar_de_empresas", "Agrupamento de Empresas", "Agrupamento de Empresas" ],
        "Açores",
            [ "presidencia_do_governo_regional_dos_acores", "Presidência", "Presidência" ],
            [ "secretario_regional_da_presidencia_raa", "Secretário da Presidência", "Secretário da Presidência" ],
            [ "vicepresidencia_emprego_e_competitividade_empresarial_raa", "Vice-Presidência", "Vice-Presidência" ],
            [ "subsecretaria_regional_da_presidencia_para_as_relacoes_externas_raa", "Relações Externas", "Relações Externas" ],
            [ "secretaria_regional_da_educacao_ciencia_e_cultura_raa", "Educação, Ciência e Cultura", "Educação, Ciência e Cultura" ],
            [ "secretaria_regional_da_saude_raa", "Saúde", "Saúde" ],
            [ "secretaria_regional_da_solidariedade_social_raa", "Solidariedade Social", "Solidariedade Social" ],
            [ "secretaria_regional_do_trabalho_e_solidariedade_social_raa", "Trabalho e Solidariedade Social", "Trabalho e Solidariedade Social" ],
            [ "secretaria_regional_do_turismo_e_transportes_raa", "Turismo e Transportes", "Turismo e Transportes" ],
            [ "secretaria_regional_dos_recursos_naturais_raa", "Recursos Naturais", "Recursos Naturais" ],
        "Madeira",
            [ "vicepresidencia__do_governo_regional_da_madeira", "Vice-Presidência", "Vice-Presidência" ],
            [ "secretaria_regional_dos_assuntos_sociais_ram", "Assuntos Sociais", "Assuntos Sociais" ],
            [ "secretaria_regional_do_plano_e_financas_ram", "Finanças e Plano", "Finanças e Plano" ],
            [ "secretaria_regional_do_ambiente_e_dos_recursos_naturais_ram", "Ambiente e Recursos Naturais", "Ambiente e Recursos Naturais" ],
            [ "secretaria_regional_da_educacao_e_recursos_humanos__ram", "Educação e Recursos Humanos", "Educação e Recursos Humanos" ],
            [ "secretaria_regional_da_cultura_turismo_e_transportes_ram", "Cultura, Turismo e Transportes", "Cultura, Turismo e Transportes" ],
        "Outros",
            [ "associacao", "Associações", "Associações" ],
            [ "cooperativa", "Cooperativas", "Cooperativas" ],
            [ "entidade_administrativa_independente", "Entidade Administrativa", "Entidade Administrativa" ],
            [ "estrutura_atipica", "Estruturas Atípicas", "Estruturas Atípicas" ],
            [ "estrutura_de_missao", "Estruturas de Missão", "Estruturas de Missão" ],
            [ "fundacao", "Fundações", "Fundações" ],
            [ "gabinete_do_representante_da_republica", "Representante da República", "Representante da República" ],
            [ "fundo_da_seguranca_social", "Fundos da Segurança Social", "Fundos da Segurança Social" ],
            [ "instituto_publico", "Institutos Públicos", "Institutos Públicos" ],
            [ "orgao_consultivo", "Órgãos Consultivos", "Órgãos Consultivos" ],
            [ "orgao_independente", "Órgãos Independentes", "Órgãos Independentes" ],
            [ "fundo_autonomo", "Fundos Autónomos", "Fundos Autónomos" ],
            [ "centro_de_formacao_profissional", "Centros de Formação Profissional", "Centros de Formação Profissional" ],
            [ "estabelecimento_de_educacao_e_ensino_basico_e_secundario", "Escolas", "Escolas" ],
            [ "forca_de_seguranca", "Forças de Segurança", "Forças de Segurança" ],
            [ "forcas_armadas", "Forças Armadas", "Forças Armadas" ]
    ]
)
